### ISSUE TITLE
파일 이름 인식 관련 문의

### ISSUE THREAD

**Issue by jjh4450** [alibreo3754/bojHelper#1]
파일 이름 인식을 정규표현식을 이용해서 XXX1205.cpp or XXX 1205.cpp와 같은 상황에서도 사용하실수 있게 해주신다면 확장의 기능이 더 풍족해질거 같아 문의 드렸습니다.

**Comment by albireo3754** [comment]
> 파일 이름 인식을 정규표현식을 이용해서 XXX1205.cpp or XXX 1205.cpp와 같은 상황에서도 사용하실수 있게 해주신다면 확장의 기능이 더 풍족해질거 같아 문의 드렸습니다.

네 반영해보겠습니다.
