### ISSUE TITLE
파이썬 파일 테스트 케이스 자동 채점 관련

### ISSUE THREAD

**Issue by mintropy** [alibreo3754/bojHelper#2]
파이썬 파일을 활용해 자동 채점 기능을 활용하는데, 문제 출력값 오류 관련 제보합니다.
파일은 `문제번호.py` 형식으로 작성했고, `ctrl + alt + t`로 자동 채점 기능을 사용하면 다음과 같이 에러 이유만 표현됩니다.
![error](https://user-images.githubusercontent.com/47909295/170830349-0a6aba7f-3231-44bb-b216-b55356dd3825.jpg)

- 이미 AC를 받은 문제도 자동 채점 기능을 사용해보았으며, 위와 같은 에러를 받습니다.

**Comment by albireo3754** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/40790219/171377971-4f120b94-0882-412d-9b2f-dd037d2e0db1.png">

혹시 문구가 다른 것 같은데 어떤버전을 사용하고 계신지요?

**Comment by mintropy** [comment]
VSC 최신 버전으로 사용하고 있고, python 3.10, 3.9, 3.7버전에서 각각 테스트 했을 때 같은 결과가 나왔습니다.

**Comment by albireo3754** [comment]
아 제가 말씀드린건 프로그램 버전을 말한건데
<img width="214" alt="image" src="https://user-images.githubusercontent.com/40790219/172110651-1bd59d8f-7f41-4e58-9496-d314884a1e0d.png">
혹시 최신버전이 맞다면 다음와 같은 VSC Extension의 임시폴더에 존재하는 캐싱된 문제에 이상이 있는지 없는지 리포트해주시면 감사하겠습니다.
<img width="739" alt="image" src="https://user-images.githubusercontent.com/40790219/172111019-a7175490-06e0-4d80-9a49-3b2e5e33eb08.png">

업데이트 하는과정에서 캐싱된 로직의 폴더 변경이 있어서 오차가 발생할수가 있어요 ㅠㅠ 임시폴더 삭제후 재설치도 한번 보고해주시면 감사합니다.

**Comment by mintropy** [comment]
앗.. 제가 잘못이해했군요, 번거롭게 해드려 죄송합니다.
![BOJhelper version](https://user-images.githubusercontent.com/47909295/172120361-9a748f40-8c2e-400d-a028-46218e5ecd46.jpg)
2.1.0버전으로 사용하고 있고, 
말씀하신 임시폴더 관련하여, 임시폴더 완전삭제 후 재설치를 하여도 같은 결과가 나옵니다. 
설치되어 있을 때, answer, problem폴더에는 올바른 입출력이 들어가있습니다. 

업데이트를 말씀하셔서 2.1.0, 2.0.0, 1.1.0, 1.0.0 버전에서 실행해보았고 처음 보고드렸던 형식으로 출력이 나옵니다. 
extension이 아니라 다른 부분에서 충돌이 발생하는걸까요??...

**Comment by albireo3754** [comment]
아닙니다 정확한 이슈트래킹이 힘들어서 문제를 해결해드릴 수 없어서 죄송하네요 ㅠ

다음에 관련된 이슈가 발견되면 그때 같이 트래킹해보도록 해보겠습니다.

**Comment by mintropy** [comment]
아이구 ㅠㅠ 넵 알겠습니다! 감사합니다!
